
import { Tour } from "./types";

export const tours: Tour[] = [
  // ETHIOPIA
  {
    id: "eth-1",
    title: "Ethiopia Adventure",
    description: "Our comprehensive 19-day flagship adventure covering the best of Ethiopia's historic and natural sites.",
    price: 1200,
    duration: "19 Days",
    location: "Ethiopia Highland & South",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?q=80&w=2000&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 156,
    tags: ["Adventure", "Culture", "History"],
  },
  {
    id: "eth-2",
    title: "Short Tour",
    description: "A quick glimpse into the beauty of Ethiopia. Perfect for busy travelers.",
    price: 150,
    duration: "1 Day",
    location: "Addis Ababa, Ethiopia",
    image: "https://images.unsplash.com/photo-1547471161-001099f0f37c?q=80&w=2000&auto=format&fit=crop",
    rating: 4.5,
    reviewsCount: 42,
    tags: ["Short Tour", "City Tour"],
  },
  {
    id: "eth-3",
    title: "City Tour",
    description: "Experience the vibrant life of Addis Ababa, searching for the soul of the city.",
    price: 100,
    duration: "1 Day",
    location: "Addis Ababa, Ethiopia",
    image: "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?q=80&w=2000&auto=format&fit=crop",
    rating: 4.6,
    reviewsCount: 89,
    tags: ["City Tour", "Culture"],
  },
  {
    id: "eth-4",
    title: "Omo Valley Trip",
    description: "Meet the unique tribes of the Omo Valley and learn about their fascinating cultures.",
    price: 850,
    duration: "6 Days",
    location: "South Ethiopia Omo Valley",
    image: "https://images.unsplash.com/photo-1518349619113-03114f06ac3a?q=80&w=2000&auto=format&fit=crop",
    rating: 4.8,
    reviewsCount: 67,
    tags: ["Culture", "Adventure"],
  },
  {
    id: "eth-5",
    title: "Axum Gheralta",
    description: "Explore the ancient stelae of Axum and the cliffside churches of Gheralta.",
    price: 450,
    duration: "3 Days",
    location: "Tigray, Ethiopia",
    image: "https://images.unsplash.com/photo-1615111784767-4a007b36f78f?q=80&w=2000&auto=format&fit=crop",
    rating: 4.7,
    reviewsCount: 34,
    tags: ["History", "Nature"],
  },
  {
    id: "eth-6",
    title: "Danakil Trip",
    description: "Visit the hottest place on earth. Volcanoes, salt flats, and sulfur springs.",
    price: 600,
    duration: "4 Days",
    location: "Afar, Ethiopia",
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=2000&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 112,
    tags: ["Adventure", "Nature"],
  },
  
  // AFRICA
  {
    id: "afr-1",
    title: "Zanzibar Paradise",
    description: "Relax on the white sand beaches and explore Stone Town's history.",
    price: 750,
    duration: "5 Days",
    location: "Zanzibar, Africa",
    image: "https://images.unsplash.com/photo-1586500036706-41963de24d8b?q=80&w=2000&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 45,
    tags: ["Beach", "Culture"],
  },
  {
    id: "afr-2",
    title: "Mombasa Getaway",
    description: "Enjoy the coastal charm of Kenya's most popular beach destination.",
    price: 650,
    duration: "4 Days",
    location: "Mombasa, Africa",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=2000&auto=format&fit=crop",
    rating: 4.7,
    reviewsCount: 23,
    tags: ["Beach", "Nature"],
  },
  
  // EUROPE
  {
    id: "eur-1",
    title: "Greece Wonders",
    description: "Athens, Santorini, and the beautiful islands of the Mediterranean.",
    price: 1200,
    duration: "7 Days",
    location: "Greece, Europe",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=2000&auto=format&fit=crop",
    rating: 4.8,
    reviewsCount: 56,
    tags: ["History", "Beach"],
  },
  {
    id: "eur-2",
    title: "France & Germany",
    description: "A dual-country tour exploring the highlights of Paris and Berlin.",
    price: 1500,
    duration: "10 Days",
    location: "Europe (France/Germany)",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=2000&auto=format&fit=crop",
    rating: 4.6,
    reviewsCount: 31,
    tags: ["History", "City Tour"],
  },
  
  // ASIA
  {
    id: "asi-1",
    title: "Thailand Explorer",
    description: "Bangkok markets, Chiang Mai temples, and the beaches of Phuket.",
    price: 900,
    duration: "8 Days",
    location: "Thailand, Asia",
    image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?q=80&w=2000&auto=format&fit=crop",
    rating: 4.7,
    reviewsCount: 92,
    tags: ["Adventure", "Culture"],
  },
  {
    id: "asi-2",
    title: "Japan Highlights",
    description: "Discover Tokyo, Kyoto, and the majestic Mount Fuji.",
    price: 1800,
    duration: "9 Days",
    location: "Japan, Asia",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2000&auto=format&fit=crop",
    rating: 4.9,
    reviewsCount: 78,
    tags: ["City Tour", "Culture", "History"],
  },
  
  // MIDDLE EAST
  {
    id: "me-1",
    title: "Dubai Luxury Experience",
    description: "Experience the world's tallest buildings and desert safaris.",
    price: 1100,
    duration: "5 Days",
    location: "Dubai, Middle East",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=2000&auto=format&fit=crop",
    rating: 4.8,
    reviewsCount: 145,
    tags: ["Adventure", "City Tour"],
  }
];
